<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArrondissementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currentTime = Carbon::now();

        $arrondissements = [
            ['nom' => 'Founougo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Gomparou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Goumori', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Kokey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Kokiborou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Ounet', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Somperoukou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Soroko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Toura', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],
            ['nom' => 'Banikoara', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 1],

            ['nom' => 'Bagou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],
            ['nom' => 'Gounarou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],
            ['nom' => 'Sori', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],
            ['nom' => 'Sougou-kpan-trossi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],
            ['nom' => 'Wara', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],
            ['nom' => 'Gogounou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 2],

            ['nom' => 'Angaradebou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Bensekou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Donwari', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Kassakou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Saah', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Sam', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Sonsoro', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Kandi 1', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Kandi 2', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],
            ['nom' => 'Kandi 3', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 3],

            ['nom' => 'Birni Lafia', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 4],
            ['nom' => 'Bogo-bogo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 4],
            ['nom' => 'Kompa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 4],
            ['nom' => 'Monsey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 4],
            ['nom' => 'Karimama', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 4],

            ['nom' => 'Garou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 5],
            ['nom' => 'Guene', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 5],
            ['nom' => 'Madecali', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 5],
            ['nom' => 'Toumboutou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 5],
            ['nom' => 'Malanville', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 5],

            ['nom' => 'Libante', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 6],
            ['nom' => 'Liboussou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 6],
            ['nom' => 'Lougou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 6],
            ['nom' => 'Sokotindji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 6],
            ['nom' => 'Segbana', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 6],

            ['nom' => 'Dipoli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Korontiere', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Koussoucoingou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Manta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Nata', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Tabota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],
            ['nom' => 'Boukoumbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 7],

            ['nom' => 'Datori', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 8],
            ['nom' => 'Kountori', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 8],
            ['nom' => 'Tapoga', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 8],
            ['nom' => 'Cobly', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 8],

            ['nom' => 'Brignamaro', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 9],
            ['nom' => 'FIROU', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 9],
            ['nom' => 'KAOBAGOU', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 9],
            ['nom' => 'KEROU', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 9],

            ['nom' => 'Birni', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],
            ['nom' => 'Chabi-couma', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],
            ['nom' => 'Foo-tance', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],
            ['nom' => 'Guilmaro', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],
            ['nom' => 'Oroukayo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],
            ['nom' => 'Kouande', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 10],

            ['nom' => 'Dassari', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],
            ['nom' => 'Gouande', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],
            ['nom' => 'Nodi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],
            ['nom' => 'Tantega', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],
            ['nom' => 'Tchanhouncossi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],
            ['nom' => 'Materi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 11],

            ['nom' => 'Kotopounga', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Kouaba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Kouandata', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Perma', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Tchoumi-tchoumi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Natitingou I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Natitingou II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Natitingou III', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],
            ['nom' => 'Peporiyakou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 12],

            ['nom' => 'Gnemasson', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 13],
            ['nom' => 'Tobre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 13],
            ['nom' => 'Pehunco', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 13],

            ['nom' => 'Cotiakou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 14],
            ['nom' => 'N\'Dahonta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 14],
            ['nom' => 'Taiacou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 14],
            ['nom' => 'Tanongou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 14],
            ['nom' => 'Tanguieta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 14],

            ['nom' => 'Kouarfa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 15],
            ['nom' => 'Tampegre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 15],
            ['nom' => 'Toukountouna', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 15],

            ['nom' => 'Akassato', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Godomey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Golo-djigbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Hevie', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Kpanroun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Ouedo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Togba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Zinvie', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],
            ['nom' => 'Abomey-Calavi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 16],

            ['nom' => 'Agbanou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Ahouannonzoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Attogon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Avakpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Ayou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Hinvi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Lissegazoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Lon-Agonmey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Sekou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Tokpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Allada Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],
            ['nom' => 'Togoudo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 17],

            ['nom' => 'Aganmalome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Agbanto', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Agonkanme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Dedome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Dekanme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Segbeya', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Segbohoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Tokpa-Dome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],
            ['nom' => 'Kpomasse Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 18],

            ['nom' => 'Avlekete', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Djegbadji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Gakpe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Houakpe-Daho', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Pahou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Savi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Ouidah I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Ouidah II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Ouidah III', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],
            ['nom' => 'Ouidah IV', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 19],

            ['nom' => 'Ahomey-Lokpo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'Dekanmey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'Ganvie 1', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'Ganvie 2', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'Houedo-Aguekon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'Vekky', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],
            ['nom' => 'So-Ava', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 20],

            ['nom' => 'Ague', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Colli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Coussi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Dame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Djanglanme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Houegbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Kpome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Sehoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Sey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],
            ['nom' => 'Toffo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 21],

            ['nom' => 'Avame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],
            ['nom' => 'Azohoue-Aliho', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],
            ['nom' => 'Azohoue-Cada', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],
            ['nom' => 'Tori-Cada', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],
            ['nom' => 'Tori-Gare', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],
            ['nom' => 'Tori-Bossito', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 22],

            ['nom' => 'Adjan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Dawe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Djigbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Dodji-Bata', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Hekanme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Koundokpoe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Sedje-Denou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Sedje-Houegoudo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Tangbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Yokpo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],
            ['nom' => 'Ze', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 23],

            ['nom' => 'Beroubouay', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 24],
            ['nom' => 'Bouanri', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 24],
            ['nom' => 'Gamia', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 24],
            ['nom' => 'Ina', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 24],
            ['nom' => 'Bembereke', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 24],

            ['nom' => 'Basso', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],
            ['nom' => 'Bouca', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],
            ['nom' => 'Derassi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],
            ['nom' => 'Dunkassa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],
            ['nom' => 'Peonga', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],
            ['nom' => 'Kalale', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 25],

            ['nom' => 'Bori', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 26],
            ['nom' => 'Gbegourou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 26],
            ['nom' => 'Ouenou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 26],
            ['nom' => 'Sirarou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 26],
            ['nom' => 'N\'Dali', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 26],

            ['nom' => 'Biro', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Gnonkourokali', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Ouenou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Serekali', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Suya', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Tasso', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],
            ['nom' => 'Nikki', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 27],

            ['nom' => '1er arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 28],
            ['nom' => '2eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 28],
            ['nom' => '3eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 28],
            ['nom' => 'Gninsy', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],
            ['nom' => 'Guinagourou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],
            ['nom' => 'Kpebie', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],
            ['nom' => 'Pane', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],
            ['nom' => 'Sontou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],
            ['nom' => 'Perere', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 29],

            ['nom' => 'Fo-boure', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 30],
            ['nom' => 'Sekere', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 30],
            ['nom' => 'Sikki', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 30],
            ['nom' => 'Sinende', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 30],

            ['nom' => 'Alafiarou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Beterou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Goro', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Kika', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Sanson', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Tchatchou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],
            ['nom' => 'Tchaourou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 31],

            ['nom' => 'Agoua', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Akpassi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Atokolibe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Bobe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Gouka', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Koko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Lougba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Pira', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],
            ['nom' => 'Bante', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 32],

            ['nom' => 'Akoffodjoule', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Gbaffo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Kere', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Kpingni', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Lema', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Paouingnan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Soclogbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Tre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Dassa I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],
            ['nom' => 'Dassa II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 33],

            ['nom' => 'Aklampa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Assante', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Gome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Kpakpaza', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Magoumi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Ouedeme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Sokponta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Thio', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Zaffe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],
            ['nom' => 'Glazoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 34],

            ['nom' => 'Challa-Ogoi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Djegbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Gbanlin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Ikemon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Kilibo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Laminou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Odougba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Toui', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],
            ['nom' => 'Ouesse', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 35],

            ['nom' => 'Djalloukou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Doume', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Gobada', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Kpataba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Lahotan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Lema', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Logozohe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Monkpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Ottola', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Ouesse', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Tchetti', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Savalou-Aga', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Savalou-Agbado', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],
            ['nom' => 'Savalou-Attake', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 36],

            ['nom' => 'Besse', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Kaboua', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Offe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Okpara', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Sakin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Adido', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Boni', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],
            ['nom' => 'Plateau', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 37],

            ['nom' => 'Atomey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Azove', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Dekpo-Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Godohou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Kissamey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Lonkly', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],
            ['nom' => 'Aplahoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 38],

            ['nom' => 'Adjintimey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Betoumey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Gohomey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Houegamey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Kinkinhoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Kokohoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Kpoba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Sokouhoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Djakotomey I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],
            ['nom' => 'Djakotomey II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 39],

            ['nom' => 'Ayomi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Deve', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Honton', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Lokogohoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Madjre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Totchangni centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],
            ['nom' => 'Tota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 40],

            ['nom' => 'Adjahonme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Ahogbeya', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Ayahohoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Djotto', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Hondjin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Lanta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Tchikpe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],
            ['nom' => 'Klouekanme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 41],

            ['nom' => 'Adoukandji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Ahodjinnako', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Ahomadegbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Banigbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Gnizounme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Hlassame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Lokogba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Tchito', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Tohou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Zalli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],
            ['nom' => 'Lalo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 42],

            ['nom' => 'Adjido', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Avedjin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Doko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Houedogli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Missinko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Tannou-Gola', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],
            ['nom' => 'Toviklin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 43],

            ['nom' => 'Aledjo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 44],
            ['nom' => 'Manigri', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 44],
            ['nom' => 'Penessoulou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 44],
            ['nom' => 'Bassila', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 44],

            ['nom' => 'Anandana', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 45],
            ['nom' => 'Pabegou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 45],
            ['nom' => 'Singre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 45],
            ['nom' => 'Copargo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 45],

            ['nom' => 'Barei', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Barienou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Bellefoungou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Bougou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Koloconde', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Onklou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Partago', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Pelebina', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Serou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Djougou I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Djougou II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],
            ['nom' => 'Djougou III', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 46],

            ['nom' => 'Badjoude', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],
            ['nom' => 'Komde', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],
            ['nom' => 'Semere 1', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],
            ['nom' => 'Semere 2', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],
            ['nom' => 'Tchalinga', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],
            ['nom' => 'Ouake', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 47],

            ['nom' => '1er arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '2eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '3eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '4eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '5eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '6eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '7eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '8eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '9eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '10eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '11eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '12eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],
            ['nom' => '13eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 48],

            ['nom' => 'Adohoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 49],
            ['nom' => 'Atchannou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 49],
            ['nom' => 'Dedekpoe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 49],
            ['nom' => 'Kpinnou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 49],
            ['nom' => 'Athieme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 49],

            ['nom' => 'Agbodji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Badazouin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Gbakpodji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Lobogo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Possotome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Yegodoe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],
            ['nom' => 'Bopa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 50],

            ['nom' => 'Agatogbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 51],
            ['nom' => 'Akodeha', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 51],
            ['nom' => 'Ouedeme-Pedah', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 51],
            ['nom' => 'Oumako', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 51],
            ['nom' => 'Come', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 51],

            ['nom' => 'Adjaha', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Agoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Avlo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Djanglanmey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Gbehoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Sazue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],
            ['nom' => 'Grand-Popo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 52],

            ['nom' => 'Dahe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],
            ['nom' => 'Doutou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],
            ['nom' => 'Honhoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],
            ['nom' => 'Zoungbonou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],
            ['nom' => 'Houeyogbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],
            ['nom' => 'Sè', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 53],

            ['nom' => 'Agame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 54],
            ['nom' => 'Houin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 54],
            ['nom' => 'Koudo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 54],
            ['nom' => 'Ouedeme-Adja', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 54],
            ['nom' => 'Lokossa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 54],

            ['nom' => 'Aglogbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],
            ['nom' => 'Honvie', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],
            ['nom' => 'Malanhoui', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],
            ['nom' => 'Mededjonou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],
            ['nom' => 'Adjarra 1', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],
            ['nom' => 'Adjarra 2', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 55],

            ['nom' => 'Akpadanou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Awonou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Azowlisse', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Deme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Gangban', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Kode', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Togbota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],
            ['nom' => 'Adjohoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 56],

            ['nom' => 'Avagbodji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 57],
            ['nom' => 'Houedome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 57],
            ['nom' => 'Zoungame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 57],

            ['nom' => 'Gome-sota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 58],
            ['nom' => 'Katagon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 58],
            ['nom' => 'Vakon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 58],
            ['nom' => 'Zoungbome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 58],
            ['nom' => 'Akpro-Misserete', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 58],

            ['nom' => 'Atchoukpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Djomon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Gbozoume', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Kouti', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Ouanho', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Sado', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],
            ['nom' => 'Avrankou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 59],

            ['nom' => 'Affame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 60],
            ['nom' => 'Atchonsa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 60],
            ['nom' => 'Dame-Wogon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 60],
            ['nom' => 'Hounvigue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 60],
            ['nom' => 'Bonou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 60],

            ['nom' => 'Dekin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Gbeko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Houedomey', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Hozin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Kessounou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Zoungue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],
            ['nom' => 'Dangbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 61],

            ['nom' => '1er arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 62],
            ['nom' => '2eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 62],
            ['nom' => '3eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 62],
            ['nom' => '4eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 62],
            ['nom' => '5eme arrondissement', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 62],

            ['nom' => 'Agblangandan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],
            ['nom' => 'Aholouyeme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],
            ['nom' => 'Djeregbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],
            ['nom' => 'Ekpe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],
            ['nom' => 'Tohoue', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],
            ['nom' => 'Seme-Podji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 63],

            ['nom' => 'Ikpinle', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],
            ['nom' => 'Kpoulou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],
            ['nom' => 'Masse', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],
            ['nom' => 'Oko-Akare', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],
            ['nom' => 'Tatonnonkon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],
            ['nom' => 'Adja-Ouere', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 64],

            ['nom' => 'Banigbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],
            ['nom' => 'Daagbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],
            ['nom' => 'Ko-Koumolou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],
            ['nom' => 'Lagbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],
            ['nom' => 'Tchaada', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],
            ['nom' => 'Ifangni', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 65],

            ['nom' => 'Adakplame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],
            ['nom' => 'Idigny', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],
            ['nom' => 'Kpankou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],
            ['nom' => 'Odometa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],
            ['nom' => 'Okpometa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],
            ['nom' => 'Ketou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 66],

            ['nom' => 'Ahoyeye', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 67],
            ['nom' => 'Igana', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 67],
            ['nom' => 'Issaba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 67],
            ['nom' => 'Towe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 67],
            ['nom' => 'Pobe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 67],

            ['nom' => 'Aguidi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],
            ['nom' => 'Ita-Djebou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],
            ['nom' => 'Takon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],
            ['nom' => 'Yoko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],
            ['nom' => 'Sakete 1', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],
            ['nom' => 'Sakete 2', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 68],

            ['nom' => 'Agbokpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Detohou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Sehoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Zounzonme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Djegbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Hounli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],
            ['nom' => 'Vidole', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 69],

            ['nom' => 'Adanhondjigo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Adingnigon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Kinta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Kpota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Lissazounme', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Sahe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Sinwe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Tanve', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Zoungoundo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],
            ['nom' => 'Agbangnizoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 70],

            ['nom' => 'Agongointo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Avogbanna', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Gnidjazoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Lissezoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Ouassaho', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Passagon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Saclo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Sodohome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Bohicon I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],
            ['nom' => 'Bohicon II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 71],

            ['nom' => 'Houeko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Adogbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Gounli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Houin-Hounso', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Lainta-Cogbe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Naogon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Soli', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],
            ['nom' => 'Zogba', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 72],

            ['nom' => 'Agondji', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Agouna', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Dan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Dohouime', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Gobaix', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Houto', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Monsourou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Mougnon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Oumbegame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Setto', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Zounkon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],
            ['nom' => 'Djidja Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 73],

            ['nom' => 'Dasso', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 74],
            ['nom' => 'Sagon', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 74],
            ['nom' => 'Tohoues', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 74],
            ['nom' => 'Ouinhi Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 74],

            ['nom' => 'Agonlin-Houegbo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],
            ['nom' => 'Baname', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],
            ['nom' => 'Don-tan', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],
            ['nom' => 'Dovi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],
            ['nom' => 'Kpedekpo', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],
            ['nom' => 'Zagnanado Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 75],

            ['nom' => 'Allahe', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Assanlin', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Houngome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Kpakpame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Kpozoun', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Za-Tanta', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Zeko', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],
            ['nom' => 'Za-Kpota', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 76],

            ['nom' => 'Akiza', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Avlame', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Cana I', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Cana II', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Dome', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Koussoukpa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Kpokissa', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Massi', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Tanwe-Hessou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Zoukou', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],
            ['nom' => 'Zogbodomey Centre', 'created_at' => $currentTime, 'updated_at' => $currentTime, 'commune_id' => 77],

        ];

        DB::table('arrondissements')->insert($arrondissements);
    }
}
